(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(abbrev-mode t)
 '(ack-prompt-for-directory t)
 '(anything-command-map-prefix-key "M-S")
 '(appt-display-format (quote window))
 '(appt-message-warning-time 10)
 '(calendar-week-start-day 1)
 '(coffee-tab-width 2)
 '(compilation-auto-jump-to-first-error nil)
 '(compilation-context-lines 10)
 '(compilation-scroll-output (quote first-error))
 '(compose-mail-user-agent-warnings nil)
 '(confirm-kill-emacs (quote yes-or-no-p))
 '(delete-selection-mode t)
 '(diary-file (concat iy-dropbox-dir "diary"))
 '(dired-dwim-target t)
 '(dired-recursive-copies (quote top))
 '(dired-recursive-deletes (quote top))
 '(doxymacs-use-external-xml-parser t)
 '(ediff-split-window-function (quote split-window-horizontally))
 '(ediff-window-setup-function (quote ediff-setup-windows-plain))
 '(eproject-completing-read-function (quote eproject--ido-completing-read))
 '(git-state-modeline-decoration (quote git-state-decoration-large-dot))
 '(highlight-symbol-idle-delay 1)
 '(highlight-symbol-on-navigation-p t)
 '(hl-paren-colors (quote ("firebrick1" "IndianRed1" "IndianRed4" "grey")))
 '(ibuffer-always-show-last-buffer :nomini)
 '(ibuffer-default-shrink-to-minimum-size t)
 '(ibuffer-jump-offer-only-visible-buffers nil)
 '(ibuffer-show-empty-filter-groups nil)
 '(install-elisp-repository-directory (concat iy-lisp-dir "3rdparty"))
 '(iy-go-to-char-key-backward 58)
 '(magit-process-popup-time 60)
 '(magit-repo-dirs (list iy-codebase-dir))
 '(magit-repo-dirs-depth 1)
 '(mail-abbrevs-mode t)
 '(mode-require-final-newline nil)
 '(mumamo-chunk-coloring 1)
 '(next-line-add-newlines nil)
 '(nxhtml-default-encoding (quote utf-8))
 '(nxhtml-skip-welcome t)
 '(pulse-delay 0.03)
 '(pulse-flag nil)
 '(pulse-iterations 5)
 '(rainbow-html-colors-major-mode-list (quote (html-mode css-mode php-mode nxml-mode xml-mode sass-mode)))
 '(reftex-default-bibliography (quote ("biblio.bib" "my.bib")))
 '(require-final-newline nil)
 '(semantic-idle-scheduler-work-idle-time 40)
 '(set-mark-command-repeat-pop t)
 '(tags-add-tables nil)
 '(tramp-default-method-alist (quote (("\\`localhost\\'" "\\`root\\'" "sudo"))))
 '(truncate-partial-width-windows nil)
 '(w3m-coding-system (quote utf-8))
 '(w3m-default-coding-system (quote utf-8))
 '(w3m-enable-google-feeling-lucky t)
 '(w3m-file-coding-system (quote utf-8))
 '(w3m-file-name-coding-system (quote utf-8))
 '(w3m-redirect-with-get t)
 '(w3m-terminal-coding-system (quote utf-8))
 '(w3m-use-cookies t)
 '(whitespace-action nil)
 '(whitespace-global-modes (quote (c-mode c++-mode makefile-gmail-mode sh-mode cmake-mode emacs-lisp-mode)))
 '(whitespace-line-column 80)
 '(whitespace-style (quote (tabs trailing lines-tail space-before-tab newline indentation space-after-tab tab-mark)))
 '(winner-dont-bind-my-keys t)
 '(winring-show-names t)
 '(woman-fontify t)
 '(woman-use-own-frame nil)
 '(woman-use-topic-at-point-default t)
 '(yas/choose-keys-first nil)
 '(yas/prompt-functions (quote (yas/dropdown-prompt yas/ido-prompt yas/x-prompt yas/no-prompt)))
 '(yas/use-menu (quote abbreviate)))

